security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: 'OU=Regional,DC=ad,DC=linedata,DC=com'
                search_dn: 'CN=SA_KenLDAP,OU=Service Accounts,OU=Global,DC=ad,DC=linedata,DC=com'
                search_password: 'LDS@ken01'
                uid_key: sAMAccountName
                filter: (sAMAccountName={username})
                default_roles: ROLE_USER
                #extra_fields: ['title']
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            security: true
            anonymous: true
            provider: my_ldap
            form_login_ldap:
                login_path: login
                check_path: login
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'sAMAccountName={username},DC=ad,DC=linedata,DC=com'
                #query_string: '(sAMAccountName={username})'
                #search_dn: 'CN=SA_KenLDAP,OU=Service Accounts,OU=Global,DC=ad,DC=linedata,DC=com'
                #search_password: 'LDS@ken01'
                default_target_path: AdminDashboard
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/AdminDashboard, roles: ROLE_USER }        

 