security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: OU=Regional,DC=ad,DC=linedata,DC=com
                search_dn: 'CN=Amina Bouslimi,OU=Users,OU=Tunisia,OU=South Europe,OU=Regional,DC=ad,DC=linedata,DC=com'
                search_password: Linedata11
                uid_key: sAMAccountName
                #extra_fields: ['dsqjdsqdhsqdsjq']
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login_ldap:
            #http_basic_ldap:
                login_path: login
                check_path: login
                service: Symfony\Component\Ldap\Ldap
                dn_string: sAMAccountName={username},OU=Users,OU=Tunisia,OU=South Europe,OU=Regional,DC=ad,DC=linedata,DC=com
                default_target_path: dashboard
                csrf_token_generator: security.csrf.token_manager
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: ROLE_USER }        

 